### ISSUE TITLE
Section 5 ResultOrWait gets error at Using System

### ISSUE THREAD

**Issue by Kenzku** [PacktPublishing/50-Things-You-ve-Been-Doing-Wrong-in-C-and-.NET-Core#1]
Hello,

I am very new in .NET. Tried to following your tutorials, looks like you do not have issue to run ResultOrWait

but when I pull down your code, and I got this error.

/usr/local/share/dotnet/sdk/3.1.200/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(59,5): error NETSDK1100: Windows is required to build Windows desktop applications.

I loaded this on Rider on Mac, but it seems other people having similar issues using system or Window on other platforms.

I tried to `dotnet restore` or other recipes found from the internet, but not able to resolve this.

Can you please explain how did you configure it and get it running. 
Thanks.

**Comment by OnurGumus** [comment]
Hello @Kenzku , although .net core is advertised as crossplatform, WPF and Windows forms are unfortunately Windows only. 
That particular example is to demonstrate UI freezes on misusing Result. So basically you need a Windows OS to execute that particular example. (Same applies to the very last chapter). Therefore I would recommend to download an evaluation copy of windows and run it in VM if you want to see that example in action. I hope it helps.

P.S You may achieve the samething with GTK# on mac probably but I haven't tried it.
